### ISSUE TITLE
Buttons from Bevy_egui

### ISSUE THREAD

**Issue by pyweeker** [belzile/tic-tac-toe#1]
Hello belzile, do you know how to integrate your game in a canvas, and have a UI around with bevy_egui ?

here is a great example, but only for Bevy0.5

https://www.basvs.dev/blog/falling-rust/?ref=https://githubhelp.com

**Comment by belzile** [comment]
I am not familiar with `bevy_egui`, but you might want to have a look at this project which does it: https://github.com/mvlabat/bevy_egui_web_showcase

For the `canvas`, this `tic-tac-to` project will work out of the box with a web page, but it will create its own canvas element as a child of the body element of your web page.

To target a specific canvas element, there is a `canvas` option somewhere on Bevy's `WindowDescriptor` (to validate (from memory)). I never tried it, but I suppose this is what it does.

**Comment by pyweeker** [comment]
thank you Belzile !
