### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AutomaticUpdates** [belzile/tic-tac-toe#2]
Hi, thank you so much for creating this project! Going through it step by step really helped me understand how bevy works.
Now I want to create an online-multiplayer version based on a modified version of your TicTacToe game. However I didn't find a license, so I wanted to ask if I could (re)-use your code, develop the game in a public repository and license it under a FOSS-license.
I have given you credit by stating your name in the `Cargo.toml` file and in my first commit.

**Comment by belzile** [comment]
Sure, I don't mind.

**Comment by AutomaticUpdates** [comment]
Thanks!
